/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface AuctionHouseInterface extends ethers.utils.Interface {
  functions: {
    "INTERFACE_ID_721()": FunctionFragment;
    "auctions(uint256)": FunctionFragment;
    "cancelAuction(uint256)": FunctionFragment;
    "createAuction(uint256,address,uint256,uint256,address,uint8,address)": FunctionFragment;
    "createBid(uint256,uint256)": FunctionFragment;
    "endAuction(uint256)": FunctionFragment;
    "minBidIncrementPercentage()": FunctionFragment;
    "setAuctionApproval(uint256,bool)": FunctionFragment;
    "setAuctionReservePrice(uint256,uint256)": FunctionFragment;
    "timeBuffer()": FunctionFragment;
    "wethAddress()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "INTERFACE_ID_721",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "auctions",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelAuction",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createAuction",
    values: [
      BigNumberish,
      string,
      BigNumberish,
      BigNumberish,
      string,
      BigNumberish,
      string
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "createBid",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "endAuction",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "minBidIncrementPercentage",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setAuctionApproval",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setAuctionReservePrice",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "timeBuffer",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "wethAddress",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "INTERFACE_ID_721",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "auctions", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "cancelAuction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createAuction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "createBid", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "endAuction", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "minBidIncrementPercentage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAuctionApproval",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAuctionReservePrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "timeBuffer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "wethAddress",
    data: BytesLike
  ): Result;

  events: {
    "AuctionApprovalUpdated(uint256,uint256,address,bool)": EventFragment;
    "AuctionBid(uint256,uint256,address,address,uint256,bool,bool)": EventFragment;
    "AuctionCanceled(uint256,uint256,address,address)": EventFragment;
    "AuctionCreated(uint256,uint256,address,uint256,uint256,address,address,uint8,address)": EventFragment;
    "AuctionDurationExtended(uint256,uint256,address,uint256)": EventFragment;
    "AuctionEnded(uint256,uint256,address,address,address,address,uint256,uint256,address)": EventFragment;
    "AuctionReservePriceUpdated(uint256,uint256,address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AuctionApprovalUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AuctionBid"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AuctionCanceled"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AuctionCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AuctionDurationExtended"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AuctionEnded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AuctionReservePriceUpdated"): EventFragment;
}

export type AuctionApprovalUpdatedEvent = TypedEvent<
  [BigNumber, BigNumber, string, boolean] & {
    auctionId: BigNumber;
    tokenId: BigNumber;
    tokenContract: string;
    approved: boolean;
  }
>;

export type AuctionBidEvent = TypedEvent<
  [BigNumber, BigNumber, string, string, BigNumber, boolean, boolean] & {
    auctionId: BigNumber;
    tokenId: BigNumber;
    tokenContract: string;
    sender: string;
    value: BigNumber;
    firstBid: boolean;
    extended: boolean;
  }
>;

export type AuctionCanceledEvent = TypedEvent<
  [BigNumber, BigNumber, string, string] & {
    auctionId: BigNumber;
    tokenId: BigNumber;
    tokenContract: string;
    tokenOwner: string;
  }
>;

export type AuctionCreatedEvent = TypedEvent<
  [
    BigNumber,
    BigNumber,
    string,
    BigNumber,
    BigNumber,
    string,
    string,
    number,
    string
  ] & {
    auctionId: BigNumber;
    tokenId: BigNumber;
    tokenContract: string;
    duration: BigNumber;
    reservePrice: BigNumber;
    tokenOwner: string;
    curator: string;
    curatorFeePercentage: number;
    auctionCurrency: string;
  }
>;

export type AuctionDurationExtendedEvent = TypedEvent<
  [BigNumber, BigNumber, string, BigNumber] & {
    auctionId: BigNumber;
    tokenId: BigNumber;
    tokenContract: string;
    duration: BigNumber;
  }
>;

export type AuctionEndedEvent = TypedEvent<
  [
    BigNumber,
    BigNumber,
    string,
    string,
    string,
    string,
    BigNumber,
    BigNumber,
    string
  ] & {
    auctionId: BigNumber;
    tokenId: BigNumber;
    tokenContract: string;
    tokenOwner: string;
    curator: string;
    winner: string;
    amount: BigNumber;
    curatorFee: BigNumber;
    auctionCurrency: string;
  }
>;

export type AuctionReservePriceUpdatedEvent = TypedEvent<
  [BigNumber, BigNumber, string, BigNumber] & {
    auctionId: BigNumber;
    tokenId: BigNumber;
    tokenContract: string;
    reservePrice: BigNumber;
  }
>;

export class AuctionHouse extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: AuctionHouseInterface;

  functions: {
    INTERFACE_ID_721(overrides?: CallOverrides): Promise<[string]>;

    auctions(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        string,
        boolean,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        number,
        string,
        string,
        string,
        string
      ] & {
        tokenId: BigNumber;
        tokenContract: string;
        approved: boolean;
        amount: BigNumber;
        duration: BigNumber;
        firstBidTime: BigNumber;
        reservePrice: BigNumber;
        curatorFeePercentage: number;
        tokenOwner: string;
        bidder: string;
        curator: string;
        auctionCurrency: string;
      }
    >;

    cancelAuction(
      auctionId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    createAuction(
      tokenId: BigNumberish,
      tokenContract: string,
      duration: BigNumberish,
      reservePrice: BigNumberish,
      curator: string,
      curatorFeePercentage: BigNumberish,
      auctionCurrency: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    createBid(
      auctionId: BigNumberish,
      amount: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    endAuction(
      auctionId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    minBidIncrementPercentage(overrides?: CallOverrides): Promise<[number]>;

    setAuctionApproval(
      auctionId: BigNumberish,
      approved: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setAuctionReservePrice(
      auctionId: BigNumberish,
      reservePrice: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    timeBuffer(overrides?: CallOverrides): Promise<[BigNumber]>;

    wethAddress(overrides?: CallOverrides): Promise<[string]>;
  };

  INTERFACE_ID_721(overrides?: CallOverrides): Promise<string>;

  auctions(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [
      BigNumber,
      string,
      boolean,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      number,
      string,
      string,
      string,
      string
    ] & {
      tokenId: BigNumber;
      tokenContract: string;
      approved: boolean;
      amount: BigNumber;
      duration: BigNumber;
      firstBidTime: BigNumber;
      reservePrice: BigNumber;
      curatorFeePercentage: number;
      tokenOwner: string;
      bidder: string;
      curator: string;
      auctionCurrency: string;
    }
  >;

  cancelAuction(
    auctionId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  createAuction(
    tokenId: BigNumberish,
    tokenContract: string,
    duration: BigNumberish,
    reservePrice: BigNumberish,
    curator: string,
    curatorFeePercentage: BigNumberish,
    auctionCurrency: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  createBid(
    auctionId: BigNumberish,
    amount: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  endAuction(
    auctionId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  minBidIncrementPercentage(overrides?: CallOverrides): Promise<number>;

  setAuctionApproval(
    auctionId: BigNumberish,
    approved: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setAuctionReservePrice(
    auctionId: BigNumberish,
    reservePrice: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  timeBuffer(overrides?: CallOverrides): Promise<BigNumber>;

  wethAddress(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    INTERFACE_ID_721(overrides?: CallOverrides): Promise<string>;

    auctions(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        string,
        boolean,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        number,
        string,
        string,
        string,
        string
      ] & {
        tokenId: BigNumber;
        tokenContract: string;
        approved: boolean;
        amount: BigNumber;
        duration: BigNumber;
        firstBidTime: BigNumber;
        reservePrice: BigNumber;
        curatorFeePercentage: number;
        tokenOwner: string;
        bidder: string;
        curator: string;
        auctionCurrency: string;
      }
    >;

    cancelAuction(
      auctionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    createAuction(
      tokenId: BigNumberish,
      tokenContract: string,
      duration: BigNumberish,
      reservePrice: BigNumberish,
      curator: string,
      curatorFeePercentage: BigNumberish,
      auctionCurrency: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    createBid(
      auctionId: BigNumberish,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    endAuction(
      auctionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    minBidIncrementPercentage(overrides?: CallOverrides): Promise<number>;

    setAuctionApproval(
      auctionId: BigNumberish,
      approved: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    setAuctionReservePrice(
      auctionId: BigNumberish,
      reservePrice: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    timeBuffer(overrides?: CallOverrides): Promise<BigNumber>;

    wethAddress(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    "AuctionApprovalUpdated(uint256,uint256,address,bool)"(
      auctionId?: BigNumberish | null,
      tokenId?: BigNumberish | null,
      tokenContract?: string | null,
      approved?: null
    ): TypedEventFilter<
      [BigNumber, BigNumber, string, boolean],
      {
        auctionId: BigNumber;
        tokenId: BigNumber;
        tokenContract: string;
        approved: boolean;
      }
    >;

    AuctionApprovalUpdated(
      auctionId?: BigNumberish | null,
      tokenId?: BigNumberish | null,
      tokenContract?: string | null,
      approved?: null
    ): TypedEventFilter<
      [BigNumber, BigNumber, string, boolean],
      {
        auctionId: BigNumber;
        tokenId: BigNumber;
        tokenContract: string;
        approved: boolean;
      }
    >;

    "AuctionBid(uint256,uint256,address,address,uint256,bool,bool)"(
      auctionId?: BigNumberish | null,
      tokenId?: BigNumberish | null,
      tokenContract?: string | null,
      sender?: null,
      value?: null,
      firstBid?: null,
      extended?: null
    ): TypedEventFilter<
      [BigNumber, BigNumber, string, string, BigNumber, boolean, boolean],
      {
        auctionId: BigNumber;
        tokenId: BigNumber;
        tokenContract: string;
        sender: string;
        value: BigNumber;
        firstBid: boolean;
        extended: boolean;
      }
    >;

    AuctionBid(
      auctionId?: BigNumberish | null,
      tokenId?: BigNumberish | null,
      tokenContract?: string | null,
      sender?: null,
      value?: null,
      firstBid?: null,
      extended?: null
    ): TypedEventFilter<
      [BigNumber, BigNumber, string, string, BigNumber, boolean, boolean],
      {
        auctionId: BigNumber;
        tokenId: BigNumber;
        tokenContract: string;
        sender: string;
        value: BigNumber;
        firstBid: boolean;
        extended: boolean;
      }
    >;

    "AuctionCanceled(uint256,uint256,address,address)"(
      auctionId?: BigNumberish | null,
      tokenId?: BigNumberish | null,
      tokenContract?: string | null,
      tokenOwner?: null
    ): TypedEventFilter<
      [BigNumber, BigNumber, string, string],
      {
        auctionId: BigNumber;
        tokenId: BigNumber;
        tokenContract: string;
        tokenOwner: string;
      }
    >;

    AuctionCanceled(
      auctionId?: BigNumberish | null,
      tokenId?: BigNumberish | null,
      tokenContract?: string | null,
      tokenOwner?: null
    ): TypedEventFilter<
      [BigNumber, BigNumber, string, string],
      {
        auctionId: BigNumber;
        tokenId: BigNumber;
        tokenContract: string;
        tokenOwner: string;
      }
    >;

    "AuctionCreated(uint256,uint256,address,uint256,uint256,address,address,uint8,address)"(
      auctionId?: BigNumberish | null,
      tokenId?: BigNumberish | null,
      tokenContract?: string | null,
      duration?: null,
      reservePrice?: null,
      tokenOwner?: null,
      curator?: null,
      curatorFeePercentage?: null,
      auctionCurrency?: null
    ): TypedEventFilter<
      [
        BigNumber,
        BigNumber,
        string,
        BigNumber,
        BigNumber,
        string,
        string,
        number,
        string
      ],
      {
        auctionId: BigNumber;
        tokenId: BigNumber;
        tokenContract: string;
        duration: BigNumber;
        reservePrice: BigNumber;
        tokenOwner: string;
        curator: string;
        curatorFeePercentage: number;
        auctionCurrency: string;
      }
    >;

    AuctionCreated(
      auctionId?: BigNumberish | null,
      tokenId?: BigNumberish | null,
      tokenContract?: string | null,
      duration?: null,
      reservePrice?: null,
      tokenOwner?: null,
      curator?: null,
      curatorFeePercentage?: null,
      auctionCurrency?: null
    ): TypedEventFilter<
      [
        BigNumber,
        BigNumber,
        string,
        BigNumber,
        BigNumber,
        string,
        string,
        number,
        string
      ],
      {
        auctionId: BigNumber;
        tokenId: BigNumber;
        tokenContract: string;
        duration: BigNumber;
        reservePrice: BigNumber;
        tokenOwner: string;
        curator: string;
        curatorFeePercentage: number;
        auctionCurrency: string;
      }
    >;

    "AuctionDurationExtended(uint256,uint256,address,uint256)"(
      auctionId?: BigNumberish | null,
      tokenId?: BigNumberish | null,
      tokenContract?: string | null,
      duration?: null
    ): TypedEventFilter<
      [BigNumber, BigNumber, string, BigNumber],
      {
        auctionId: BigNumber;
        tokenId: BigNumber;
        tokenContract: string;
        duration: BigNumber;
      }
    >;

    AuctionDurationExtended(
      auctionId?: BigNumberish | null,
      tokenId?: BigNumberish | null,
      tokenContract?: string | null,
      duration?: null
    ): TypedEventFilter<
      [BigNumber, BigNumber, string, BigNumber],
      {
        auctionId: BigNumber;
        tokenId: BigNumber;
        tokenContract: string;
        duration: BigNumber;
      }
    >;

    "AuctionEnded(uint256,uint256,address,address,address,address,uint256,uint256,address)"(
      auctionId?: BigNumberish | null,
      tokenId?: BigNumberish | null,
      tokenContract?: string | null,
      tokenOwner?: null,
      curator?: null,
      winner?: null,
      amount?: null,
      curatorFee?: null,
      auctionCurrency?: null
    ): TypedEventFilter<
      [
        BigNumber,
        BigNumber,
        string,
        string,
        string,
        string,
        BigNumber,
        BigNumber,
        string
      ],
      {
        auctionId: BigNumber;
        tokenId: BigNumber;
        tokenContract: string;
        tokenOwner: string;
        curator: string;
        winner: string;
        amount: BigNumber;
        curatorFee: BigNumber;
        auctionCurrency: string;
      }
    >;

    AuctionEnded(
      auctionId?: BigNumberish | null,
      tokenId?: BigNumberish | null,
      tokenContract?: string | null,
      tokenOwner?: null,
      curator?: null,
      winner?: null,
      amount?: null,
      curatorFee?: null,
      auctionCurrency?: null
    ): TypedEventFilter<
      [
        BigNumber,
        BigNumber,
        string,
        string,
        string,
        string,
        BigNumber,
        BigNumber,
        string
      ],
      {
        auctionId: BigNumber;
        tokenId: BigNumber;
        tokenContract: string;
        tokenOwner: string;
        curator: string;
        winner: string;
        amount: BigNumber;
        curatorFee: BigNumber;
        auctionCurrency: string;
      }
    >;

    "AuctionReservePriceUpdated(uint256,uint256,address,uint256)"(
      auctionId?: BigNumberish | null,
      tokenId?: BigNumberish | null,
      tokenContract?: string | null,
      reservePrice?: null
    ): TypedEventFilter<
      [BigNumber, BigNumber, string, BigNumber],
      {
        auctionId: BigNumber;
        tokenId: BigNumber;
        tokenContract: string;
        reservePrice: BigNumber;
      }
    >;

    AuctionReservePriceUpdated(
      auctionId?: BigNumberish | null,
      tokenId?: BigNumberish | null,
      tokenContract?: string | null,
      reservePrice?: null
    ): TypedEventFilter<
      [BigNumber, BigNumber, string, BigNumber],
      {
        auctionId: BigNumber;
        tokenId: BigNumber;
        tokenContract: string;
        reservePrice: BigNumber;
      }
    >;
  };

  estimateGas: {
    INTERFACE_ID_721(overrides?: CallOverrides): Promise<BigNumber>;

    auctions(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    cancelAuction(
      auctionId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    createAuction(
      tokenId: BigNumberish,
      tokenContract: string,
      duration: BigNumberish,
      reservePrice: BigNumberish,
      curator: string,
      curatorFeePercentage: BigNumberish,
      auctionCurrency: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    createBid(
      auctionId: BigNumberish,
      amount: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    endAuction(
      auctionId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    minBidIncrementPercentage(overrides?: CallOverrides): Promise<BigNumber>;

    setAuctionApproval(
      auctionId: BigNumberish,
      approved: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setAuctionReservePrice(
      auctionId: BigNumberish,
      reservePrice: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    timeBuffer(overrides?: CallOverrides): Promise<BigNumber>;

    wethAddress(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    INTERFACE_ID_721(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    auctions(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    cancelAuction(
      auctionId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    createAuction(
      tokenId: BigNumberish,
      tokenContract: string,
      duration: BigNumberish,
      reservePrice: BigNumberish,
      curator: string,
      curatorFeePercentage: BigNumberish,
      auctionCurrency: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    createBid(
      auctionId: BigNumberish,
      amount: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    endAuction(
      auctionId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    minBidIncrementPercentage(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setAuctionApproval(
      auctionId: BigNumberish,
      approved: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setAuctionReservePrice(
      auctionId: BigNumberish,
      reservePrice: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    timeBuffer(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    wethAddress(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
